name: .NET CI/CD

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      # Check commit messages for Conventional Commits schema
      - name: Lint Commits
        uses: wagoid/commitlint-github-action@v4
        with:
          configFile: commitlint.config.js  # Optional if you have custom rules
      
      # Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore
      
      # Run dotnet-format for code style checks
      - name: Run Code Linting
        run: dotnet format MindWeb.sln --verify-no-changes
      
      # Build project
      - name: Build
        run: dotnet build --no-restore
      
      # Test project
      - name: Test
        run: dotnet test --no-build --verbosity normal
