name: .NET CI/CD

env:
  AZURE_WEBAPP_NAME: MindWeb

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Check commit messages for Conventional Commits schema
      - name: Lint Commits
        uses: wagoid/commitlint-github-action@v4
        with:
          configFile: commitlint.config.js
      
      # Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Run dotnet-format for code style checks
      - name: Run Code Linting
        run: dotnet format MindWeb.sln --verify-no-changes

      # Build project
      - name: Build
        run: dotnet build --no-restore

      # Test project
      - name: Test
        run: dotnet test --no-build --verbosity normal

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image for Frontend
      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t ghcr.io/teddy55codes/mindweb-frontend:${{ github.sha }} -f ./MindWeb.Frontend/Dockerfile ./ 
          docker push ghcr.io/teddy55codes/mindweb-frontend:${{ github.sha }}
          docker build -t ghcr.io/teddy55codes/mindweb-frontend:latest -f ./MindWeb.Frontend/Dockerfile ./ 
          docker push ghcr.io/teddy55codes/mindweb-frontend:latest

      # Build and push Docker image for API
      - name: Build and Push API Docker Image
        run: |
          docker build -t ghcr.io/teddy55codes/mindweb-api:${{ github.sha }} -f ./MindWeb.API/Dockerfile ./
          docker push ghcr.io/teddy55codes/mindweb-api:${{ github.sha }}
          docker build -t ghcr.io/teddy55codes/mindweb-api:latest -f ./MindWeb.API/Dockerfile ./
          docker push ghcr.io/teddy55codes/mindweb-api:latest
  
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'ghcr.io/teddy55codes/mindweb-frontend:${{ github.sha }}'